### ISSUE TITLE
source.json文件怎么使用的

### ISSUE THREAD

**Issue by shichuanenhui** [Guovin/TV#1]
1、source.json文件怎么使用的，在代码里没看到哪块使用，
2、source.json里面的源内容配置能否不配置{ http://饭太硬.top/tv}，而配置里面的直播链接
https://mirror.ghproxy.com/raw.githubusercontent.com/dxawi/0/main/tvlive.txt，或者配置两种都支持
3、这个source.json配置的数据源会把里面的lives的直播源都遍历一遍吗? 再去筛选出有效的整合成一个文件吗？还是去{http://tonkiang.us}这个网站根据电视台名字去搜索，然后获取出来m3u8链接放到result.txt里
![微信截图_20240229172333](https://github.com/Guovin/TV/assets/16698731/90cd9ecc-e56b-428d-bb02-9d7fb30ec939)
4、获取回来的同名源，比如CCTV1有15个源，是咋排序的，清晰度最高，速度最快的放到第一个吗？
感谢大佬解答

**Comment by Guovin** [comment]
1.source.json为数据源文件，仅为分享作用，不作用于接口更新，可自行修改
2.目前权重最高为按分辨率越高排序越靠前，后续将开放自定义权重进行排序

**Comment by shichuanenhui** [comment]
意思就是source.json里面的内容对result.txt结果没任何影响，只是demo.txt里面的内容和{http://tonkiang.us} 根据demo.txt里面的电视台名时时搜索出来的内容有影响是吧

**Comment by Guovin** [comment]
> 1.source.json为数据源文件，仅为分享作用，不作用于接口更新，可自行修改 2.目前权重最高为按分辨率越高排序越靠前，后续将开放自定义权重进行排序

#6 已开放配置：响应时间、分辨率权重值排序、时间范围过滤

**Comment by shichuanenhui** [comment]
厉害厉害
