### ISSUE TITLE
gd上自动跑失败了？

### ISSUE THREAD

**Issue by kimwang1978** [Guovin/TV#105]
前面2个手动跑都跑通了，之后2天的job自动跑好像都失败了。

**Comment by kimwang1978** [comment]
好像自动跑还是走master了？

**Comment by LuckyLearning** [comment]
@kimwang1978 
文件路径：.github/workflows/release.yml
name: Release
on:
  workflow_dispatch:
    branches:
      - master
把这个改成：
name: Release
on:
  workflow_dispatch:
    branches:
      - gd

**Comment by Guovin** [comment]
已解决，请更新最新版本，源仓库默认使用gd分支更新，fork仓库默认使用master分支
