### ISSUE TITLE
同步到1.2后，不能正常生成user_result.txt文件

### ISSUE THREAD

**Issue by kimwang1978** [Guovin/TV#132]
user_config.py配置到最新的了，哪里漏配了么……望指教。

**Comment by Guovin** [comment]
看了一下你的更新记录，因为github只有更新结果发生变化，与上一次更新有差异才会形成新的文件，否则会使用上一次的结果文件。目前线上查询功能有点问题，等我优化。

**Comment by kimwang1978** [comment]
> 看了一下你的更新记录，因为github只有更新结果发生变化，与上一次更新有差异才会形成新的文件，否则会使用上一次的结果文件。目前线上查询功能有点问题，等我优化。

好的，多谢！

**Comment by Guovin** [comment]
#143 已暂时修复线上查询功能，线上查询更新速度会有点慢，待下一版优化

**Comment by Guovin** [comment]
> #143 已暂时修复线上查询功能，线上查询更新速度会有点慢，待下一版优化

#176 已优化上线
