### ISSUE TITLE
docker配置能做个路径吗

### ISSUE THREAD

**Issue by Yumega** [Guovin/TV#206]
安装后根本找不到配置文件的路径

**Comment by Guovin** [comment]
目前默认的工作目录是/app，默认配置位于/app/config.py。你可以在创建容器时自定义工作目录，通过添加-w命令：
```bash
docker run -w /工作目录名称 --name tv-requests或driver -d -p 8000:8000 guovern/tv-requests或driver

**Comment by Guovin** [comment]
#213 已支持目录映射，-v 宿主机路径/TV:/tv-requests 或 tv-driver，requests默认目录：/tv-requests，driver默认目录：/tv-driver
