### ISSUE TITLE
docker运行映射目录的问题

### ISSUE THREAD

**Issue by vbskycn** [Guovin/TV#207]
看介绍是用copy   demo到docker容器内的方法
用映射的方法不是更好吗？

docker run --name tv-requests --restart unless-stopped -d -p 8000:8000 \
  -v /root/docker/guovin-tv/config.py:/app/config.py \
  -v /root/docker/guovin-tv/demo.txt:/app/demo.txt \
  -v /root/docker/guovin-tv/result.txt:/app/result.txt \
  guovern/tv-requests

这样是不是会有什么问题？？
运行成功后只有访问/root/docker/guovin-tv/result.txt就是想要的列表了，而且docker内可以定时时运行，这样只要设置一下主机的config.py，就完全不用管了，定时查看result.txt就可以了，还可以定时把result.txt同步到网站目录，这就完全自动了

**Comment by Guovin** [comment]
卷挂载确实是一个好的实践，但经测试还是存在一些问题:
1. 当宿主机不存在模板、配置文件和结果文件时，启动容器会自动创建该文件名的文件夹，这并不是我们想要的。
2. 如果我们预先在宿主机新建了这些文件，也必须含有正确的内容，否则宿主机的空白内容会直接覆盖容器内的文件内容，或许我们更想要的是启动时来自容器内的默认配置。

基于上述问题，挂载整个目录会比较好一些:
```bash
-v /root/docker/guovin-tv:/app
```
后面增加修改工作目录的环境变量也会方便使用挂载。

**Comment by vbskycn** [comment]
那可否先clone，再挂载目录致app目录，里面的文件应该是和github同步的吧，这样也可以达到目的，最少比copy要方便一些，主机可以直接访问还是要方便，可以设置为web目录，直接可以用主机的nginx了，就不用容器里面在开启一个nginx服务了

**Comment by Guovin** [comment]
> 那可否先clone，再挂载目录致app目录，里面的文件应该是和github同步的吧，这样也可以达到目的，最少比copy要方便一些，主机可以直接访问还是要方便，可以设置为web目录，直接可以用主机的nginx了，就不用容器里面在开启一个nginx服务了

是的，这样是最好的，但要兼顾不clone直接使用镜像的人群

**Comment by Guovin** [comment]
#213 v1.3.3已支持卷挂载目录映射
