### ISSUE TITLE
actions运行问题

### ISSUE THREAD

**Issue by zzz0121** [Guovin/TV#208]
运行成功，但是只生成了log文件，没有找到user_result.txt文件，还是说生成了，我没有找到路径

**Comment by zzz0121** [comment]
![Snipaste_2024-07-14_13-38-47](https://github.com/user-attachments/assets/aa6de709-609a-45c5-aecb-7c082d0a15b4)

**Comment by zzz0121** [comment]
为啥会检测不到数据呀

**Comment by Guovin** [comment]
若获取不到更新，请开启driver:
```python
open_driver=True
```

**Comment by zzz0121** [comment]
![image](https://github.com/user-attachments/assets/3a3e77ad-5ed0-4395-a9c8-a8d5aaf51bb8)
是这些吗

**Comment by zzz0121** [comment]
一开始就是开着的

**Comment by Guovin** [comment]
修改你的user_config.py

**Comment by zzz0121** [comment]
修改了这个，额，又运行了两遍，还是没有数据，并且没有生成txt资源文件
![image](https://github.com/user-attachments/assets/de4c6b7d-fb79-4f6f-bb4a-3027eb91952a)

**Comment by Guovin** [comment]
拉取最新代码，重新试一下

**Comment by zzz0121** [comment]
不行呀，佬，😂
![image](https://github.com/user-attachments/assets/251fe8a4-903d-451c-a029-63d352781e65)

**Comment by zzz0121** [comment]
![Uploading IMG_20240716_102747.jpg…]()

**Comment by zzz0121** [comment]
![image](https://github.com/user-attachments/assets/41e4a5df-b433-46c8-a8fb-51a36c96e91e)

**Comment by Guovin** [comment]
#210 #211 更新代码，再运行试试

**Comment by zzz0121** [comment]
这下可以了，佬，方便指导一下为什么会这个样子吗，修改的哪些文件

**Comment by zzz0121** [comment]
扫描的源文件在哪里可以更改，我看配置的脚本里有不知道是不是那个

**Comment by Guovin** [comment]
> 这下可以了，佬，方便指导一下为什么会这个样子吗，修改的哪些文件

读取用户配置有点问题，优化处理了。

> 扫描的源文件在哪里可以更改，我看配置的脚本里有不知道是不是那个

我不太清楚你说的“扫描的源文件”是什么意思，如果是在线搜索的数据来源目前无法自定义，订阅源可以自定义（subscribe_urls），模板文件名称配置（source_file），具体可以看[参数配置介绍](https://github.com/Guovin/TV/blob/master/docs/config.md)

**Comment by zzz0121** [comment]
ok，谢谢
