### ISSUE TITLE
更新源的问题

### ISSUE THREAD

**Issue by yxcqr** [Guovin/TV#224]
老板您好！
        每次都把update-tool.exe，更新到最新版，设置那些也多次确认无误，
就算把上一次更新的所有文件全部删除，再换个目录，再次更新，但是更新出来的直播，全部都没有变化，
连续几个版本就是这种情况，而且更新出来的源，大多失败，无法播放，
不知道是哪里的问题，

Windows下，直接运行更新的。

**Comment by Guovin** [comment]
如果获取不到更新结果，请打开浏览器模式后运行更新

**Comment by yxcqr** [comment]
感谢老板指导，之前也试过开浏览器模式，也是没有成功，
今天又试了一下，把之前的配置文件全部删除掉，只留下update-tool.exe，
设置好参数，就能正常更新了，
感谢老板分享，解答。
