### ISSUE TITLE
无法更新问题

### ISSUE THREAD

**Issue by kakaxi-1** [Guovin/TV#225]
按照“方式四：工作流更新 Fork 本项目并开启工作流更新”，user_result.txt文件下没有生产新的，请求帮助

**Comment by Guovin** [comment]
master目前默认使用requests模式运行，如遇更新失效情况，可修改config的open_driver = True后重新运行

**Comment by kakaxi-1** [comment]
> master目前默认使用requests模式运行，如遇更新故障情况，可修改config的open_driver = True后重新运行

帮忙看看我的是不是有什么问题没有弄好，改了后重新运行还是没有更新

**Comment by kakaxi-1** [comment]
> master目前默认使用requests模式运行，如遇更新故障情况，可修改config的open_driver = True后重新运行

已经解决正常运行更新，组播抓取不是很准确，能在tonkiang.us上自动抓取替换最新IP就好了

**Comment by Guovin** [comment]
> > master目前默认使用requests模式运行，如遇更新故障情况，可修改config的open_driver = True后重新运行
> 
> 已经解决正常运行更新，组播抓取不是很准确，能在tonkiang.us上自动抓取替换最新IP就好了

此功能正在开发，预计下一版本支持

**Comment by Guovin** [comment]
> > master目前默认使用requests模式运行，如遇更新故障情况，可修改config的open_driver = True后重新运行
> 
> 已经解决正常运行更新，组播抓取不是很准确，能在tonkiang.us上自动抓取替换最新IP就好了

v1.3.5已支持
