### ISSUE TITLE
关于docker运行的问题

### ISSUE THREAD

**Issue by QAQQL** [Guovin/TV#226]
建议生成的文件和配置的文件在一个单独的文件夹,比如
/tv-driver/output
/tv-driver/config
这样映射只需要映射子文件夹,就不会提示脚本不存在了

```
实现宿主机文件与容器文件同步，修改模板、配置、获取更新结果文件可直接在宿主机文件夹下操作
注：使用此命令运行容器，请务必先clone本项目至宿主机
```

**Comment by QAQQL** [comment]
感谢

**Comment by Guovin** [comment]
> 建议生成的文件和配置的文件在一个单独的文件夹,比如 /tv-driver/output /tv-driver/config 这样映射只需要映射子文件夹,就不会提示脚本不存在了
> 
> ```
> 实现宿主机文件与容器文件同步，修改模板、配置、获取更新结果文件可直接在宿主机文件夹下操作
> 注：使用此命令运行容器，请务必先clone本项目至宿主机
> ```

这是一个很好的建议，功能已实现，等待新的镜像上传后即可使用。

**Comment by Guovin** [comment]
> > 建议生成的文件和配置的文件在一个单独的文件夹,比如 /tv-driver/output /tv-driver/config 这样映射只需要映射子文件夹,就不会提示脚本不存在了
> > ```
> > 实现宿主机文件与容器文件同步，修改模板、配置、获取更新结果文件可直接在宿主机文件夹下操作
> > 注：使用此命令运行容器，请务必先clone本项目至宿主机
> > ```
> 
> 这是一个很好的建议，功能已实现，等待新的镜像上传后即可使用。

镜像已上传
