### ISSUE TITLE
你这个rtp地址如何转成m3u的呢，或者说这个直播源怎么用

### ISSUE THREAD

**Issue by seitaone** [Guovin/TV#317]
你这个rtp地址如何转成m3u的呢，或者说这个直播源怎么用

**Comment by Guovin** [comment]
rtp地址是频道固定的地址，不易失效，可以自行维护。程序获取的是比较容易失效的各地区运营商的ip，生成可播放的组播接口，有频道名称和接口就可以转换成m3u。有多种使用方法，比较简单的是工作流运行或软件运行，然后复制链接到播放软件就可以播放了，具体使用可以查看教程。
