### ISSUE TITLE
本地运行出现不支持IPV6 bug

### ISSUE THREAD

**Issue by FRANKASEE** [Guovin/TV#328]
运行提示：our network does not support IPv6, using proxy

V6检测结果：

您的互联网服务提供商（ISP）看起来是 CHINANET-SH-AP China Telecom Group, CN

既然你有IPv6，我们就显示一个选项卡，显示您可以前往的其他IPv6网站。[[更多信息]](http://ipv6-test.ch/#)

好消息!您当前位置当前电脑上的浏览器，预计将在IPv6启动之后继续正常运行。

检测到NAT64。IPv6工作。IPv4在大多数目的下工作。应用程序被硬编码为仅IPv4将失败。我们知道有至少一种常用的IP语音应用程序属于此类。您的应用程序的支持人员可能需要微调，适当增加对IPv6的支持。

您的DNS服务器(通常由您的网络服务商提供)已经可以接入IPv6互联网了。

**Comment by Guovin** [comment]
#330 已优化，请更新v1.4.6
