### ISSUE TITLE
m3u中存在使用错误的地址

### ISSUE THREAD

**Issue by zid99825** [Guovin/TV#329]
CCTV-5+频道中出现以下地址，地址本身可响应，但返回内容中存在404错误

Name: CCTV-5+, URL: http://220.179.68.222:9901/tsfile/live/0016_1.m3u8?key=txiptv&playlive=1&authid=0, Date: None, Resolution: None, Response Time: 34 ms

`{"timestamp":"2024-09-20T17:08:33.979+0800","status":404,"error":"Not Found","message":"Not Found","path":"/tsfile/live/0016_1.m3u8"}`

是否有办法过滤此类频道？因为生成m3u会默认用Response Time最短的地址？

**Comment by Guovin** [comment]
#330 已优化，请更新v1.4.6
