### ISSUE TITLE
docker运行出错

### ISSUE THREAD

**Issue by aweder** [Guovin/TV#357]
在docker环境下运行无法启动，日志报：exec /bin/sh: exec format error

**Comment by Guovin** [comment]
检查你的系统是否存在bash：
```shell
ls -l /bin/bash
```
如果只有dash，则需要做软连接：
```shell
ln -s /bin/dash /bin/bash
```

**Comment by aweder** [comment]
有bash:
root@armbian:~# ls -l /bin/bash
-rwxr-xr-x 1 root root 1346480 Mar 30  2024 /bin/bash
能查询找，不知道是哪里有问题

**Comment by Guovin** [comment]
检查你的虚拟机架构版本是否与镜像匹配
