### ISSUE TITLE
自定义demo文件不生效

### ISSUE THREAD

**Issue by zzz0121** [Guovin/TV#358]
1. 自定义文件
![image](https://github.com/user-attachments/assets/322cccf7-6657-4eef-80fa-556e00f9a16d)
生成文件
![image](https://github.com/user-attachments/assets/52079d54-d9a6-411b-a273-9700480f2111)
2. 还有就是生成播放链接最前面有的不能使用CCTV2
![image](https://github.com/user-attachments/assets/40a37117-d79d-402a-b897-efe0289af036)
![Screenshot_2024-10-02-17-20-35-005_com huawei him](https://github.com/user-attachments/assets/c3e910fe-9cbe-4f07-8672-68cb5b49d29b)
3. 可能还是跟第一个问题一样，扫描了很多自定义文件没有的节目台
![image](https://github.com/user-attachments/assets/eff5c3c2-f510-4878-82f4-3fba36efb6d5)

下面是我的自定义文件规则配置
![image](https://github.com/user-attachments/assets/2632c1f5-19b7-43da-82b7-5f9b7453ae97)

**Comment by zzz0121** [comment]
还有一个就是生成的m3u文件相同的台在视频软件中没有合并为一个，生成的txt文件就合成了一个

**Comment by Guovin** [comment]
1.你的模板文件是user_demo.txt，配置中应该将source_file的值改为config/user_demo.txt，默认模板文件是demo.txt
2.接口为网络收集，只能判断能否播放，而无法判断内容是否可用
3.同1
4.m3u没有合并是软件问题，建议更换软件尝试，比如影视仓、影迷

**Comment by zzz0121** [comment]
ok，感谢楼主，问题已解决
请问配置文件中这些订阅链接是干啥的
![image](https://github.com/user-attachments/assets/56cbee7f-15bb-42d1-9dc4-9b813da3397d)

**Comment by Guovin** [comment]
> ok，感谢楼主，问题已解决 请问配置文件中这些订阅链接是干啥的 ![image](https://private-user-images.githubusercontent.com/132324908/372831449-56cbee7f-15bb-42d1-9dc4-9b813da3397d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NjU4MzksIm5iZiI6MTcyNzg2NTUzOSwicGF0aCI6Ii8xMzIzMjQ5MDgvMzcyODMxNDQ5LTU2Y2JlZTdmLTE1YmItNDJkMS05ZGM0LTliODEzZGEzMzk3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQxMDM4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjRlYTMwNzU0MTgwMzIwZDJkYzFhYWYwMGI2ODNiODcwMWJlNmZmMzY5ZGE2OWUxNmQ0MjE0YzdhNGVlMjkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KQGCxXdGKAqde4i3vRZHx5oXzGYfMdk71d7Brq4jl2g)

订阅源功能执行的链接，你可以添加别人的接口源链接地址，程序运行会从这些链接中提取符合你模板中定义的频道接口

**Comment by zzz0121** [comment]
额额，明白了，也就是说咱们现在自动更新也是搜索这些订阅链接是否更新可以这样理解吧

**Comment by Guovin** [comment]
> 额额，明白了，也就是说咱们现在自动更新也是搜索这些订阅链接是否更新可以这样理解吧

是的，提取里面可用的接口，但这只是来源的一部分，默认开启的组播源和酒店源则是主要的接口来源

**Comment by zzz0121** [comment]
ok，学习学习，谢谢
