### ISSUE TITLE
[提议]Docker网页result直接输出m3u 和 txt

### ISSUE THREAD

**Issue by joejoe0243** [Guovin/TV#386]
现在的result是一个HTML, 不能直接导入网址
建议直接输出m3u和txt

**Comment by Guovin** [comment]
不太清楚你的问题描述，目前是支持输出m3u/txt文件和页面的

**Comment by joejoe0243** [comment]
现时页面不是一个正规的m3u, 只是一个HTML, 不能直接在播放器导入
希望能够输出m3u/txt页面

**Comment by Guovin** [comment]
你把地址复制到播放器试试，是可以播放的

**Comment by Guovin** [comment]
提醒一下，地址后缀你如果添加了/result查看的是文件的文本内容，/log查看的是日志内容，播放器使用需要去除地址的/result

**Comment by joejoe0243** [comment]
明白, 谢谢
