### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by moonkeyhoo** [Guovin/TV#387]
我的网络是陕西联通，更新时比别人慢很多，主要是到了TONKING组播阶段，别人一共用几分钟就全部完成，我的是要30多分钟，我是台式机，本地搜索，自己整理。

**Comment by moonkeyhoo** [comment]
不知道什么原因？杀毒关闭
![Uploading 无标题.png…]()

**Comment by Guovin** [comment]
有修改过配置吗？默认使用driver浏览器模式会比requests慢的

**Comment by moonkeyhoo** [comment]
在路上
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Guovin/TV"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月14日(星期一) 上午9:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Guovin/TV] 问题 (Issue #387)





 
有修改过配置吗？默认使用driver浏览器模式会比requests慢的

**Comment by moonkeyhoo** [comment]
首先感谢大佬的无私分享，给更多的人带来了方便。我想请教一下，怎么在docker中部署你共享的软件，并且按定时启动工作，能给我发一份部署教程吗？还有在青龙面板中的脚本对于我来说比较难，有无指导教程？




在路上
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Guovin/TV"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月14日(星期一) 上午9:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Guovin/TV] 问题 (Issue #387)





 
有修改过配置吗？默认使用driver浏览器模式会比requests慢的

**Comment by Guovin** [comment]
1. docker部署按照首页或详细教程中的docker运行方式部署即可，拉取镜像、启动容器、访问结果，容器已经默认包含了每日自动更新两次的定时任务，无需更多处理；
2. 关于青龙，我并没有用过，抱歉不能提供更多的详细帮助。从我听到别人的反馈，可以将项目clone下载，复制至青龙中，使用项目中的main.py文件运行即可。如果你需要手动定义定时任务，每次运行完成后能停止程序，按青龙的定时任务执行，当前单次更新完成后你需要手动中止。为了优化这个问题，请等待下次版本更新，我将增加移除默认的程序定时任务和不启动页面服务的配置项。

**Comment by Guovin** [comment]
请把你的模板和报错日志发出来

**Comment by Guovin** [comment]
飞牛也有docker，可以按docker的步骤进行部署，拉取镜像记得开启代理

**Comment by moonkeyhoo** [comment]
在路上
***@***.***



&nbsp;


版本更新刚解决，又出现新版本不能拉取，是要间隔24小时以上吗？

**Comment by Guovin** [comment]
> 在路上 ***@***.*** &nbsp; 版本更新刚解决，又出现新版本不能拉取，是要间隔24小时以上吗？

不需要，检查你的网络

**Comment by moonkeyhoo** [comment]
在路上
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Guovin/TV"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月6日(星期三) 下午3:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Guovin/TV] 问题 (Issue #387)





  
在路上 @.*** &nbsp; 版本更新刚解决，又出现新版本不能拉取，是要间隔24小时以上吗？
  
不需要，检查你的网络

**Comment by moonkeyhoo** [comment]
好吧




在路上
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Guovin/TV"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月6日(星期三) 下午3:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Guovin/TV] 问题 (Issue #387)





  
在路上 @.*** &nbsp; 版本更新刚解决，又出现新版本不能拉取，是要间隔24小时以上吗？
  
不需要，检查你的网络

**Comment by moonkeyhoo** [comment]
155版本开始出现这样的情况？


在路上
***@***.***



新版本，摸索部署和使用。目前有两个问题：1.显示时间内外不一致。2.每日更新时间貌似是晚上19：00-19：40左右，影响电视观看，不知道能不能把更新时间改为凌晨4：00-5：00或者下午16：00-17：00，避开电视使用时间和网络拥堵时段。2.扫描完成后，内存持续增高，仍旧在上传下载，但是没有实际文件，不知道是什么原因？
