### ISSUE TITLE
想问下订阅源不支持m3u吗

### ISSUE THREAD

**Issue by mcnk328** [Guovin/TV#389]
软件内预置的订阅源清空后改成别的源，源文件都是m3u的，并且关闭了酒店源和组播，结果输出的节目列表为空

**Comment by Guovin** [comment]
不支持，目前仅支持txt文件链接

**Comment by Guovin** [comment]
已实现，请更新v1.5.0

**Comment by mcnk328** [comment]
> 已实现，请更新v1.5.0

感谢
