### ISSUE TITLE
纯组播源获取不到

### ISSUE THREAD

**Issue by mlzlzj** [Guovin/TV#402]
将config文件内获取酒店源的选项设置为false后，只保留获取组播源为true后获取不到任何频道列表。

**Comment by mlzlzj** [comment]
原因找到了，不是代码的问题，使我们湖南扫不到什么组播源，特别是代码里面过滤掉了udp就更没什么了，希望能在config.ini文件里可以设置是否保留udp的组播源。

**Comment by mlzlzj** [comment]
好像代码不能解析域名下的频道列表吧，像dak3yy7y.mi4.xyz:8888这种域名下的频道列表如果能解析的话会多很多频道列表，湖南的组播有很多是在类似这些域名下的，而且是udp的，希望大佬能升级下代码，致谢！

**Comment by Guovin** [comment]
并没有相关过滤udp的处理，如果你想要获取某个域名地址下的接口，请将该地址添加到订阅（subscribe_urls），目前是支持获取的
