### ISSUE TITLE
有办法把这些相同的频道合并在一起么？影视仓

### ISSUE THREAD

**Issue by chinasb** [Guovin/TV#403]
![cd1591f941ccbcd627f10de819d2c24](https://github.com/user-attachments/assets/66d30e41-e97d-421e-ac40-13d67f78509d)

**Comment by Guovin** [comment]
软件问题，好像影视仓使用m3u地址会有这种情况，你试试txt应该没有问题，实在不行只能换软件了

**Comment by chinasb** [comment]
我在main.py 中加了几行代码, 对其他功能不影响, 还解决了影视仓出现的这个问题,
```
@app.route("/txt")
def show_txt():
    user_final_file = "output/result.txt"
    return send_file(user_final_file)
```
配置是填写 http://yourid:8000/txt

**Comment by Guovin** [comment]
没必要修改代码，本来就支持输出txt结果，修改配置open_m3u_result = False，即可使用http://yourid:8000就可以访问txt结果。

**Comment by Giresharu** [comment]
kodi 用 iptv 插件也是这个问题，好像不能用 txt
potplayer 也是
难受了
![Snipaste_2024-10-25_03-07-30](https://github.com/user-attachments/assets/d3520e1d-6cd1-4125-b130-882653f9b405)

**Comment by Guovin** [comment]
> > kodi 用 iptv 插件也是这个问题，好像不能用 txt potplayer 也是 难受了
> 
> 看下其他能合并的源的格式是什么样的，想办法改成他们那种格式？

是的，看一下该类播放器支持合并的结果格式是怎么样的，我看看能不能支持

**Comment by Giresharu** [comment]
> > > kodi 用 iptv 插件也是这个问题，好像不能用 txt potplayer 也是 难受了
> > 
> > 
> > 看下其他能合并的源的格式是什么样的，想办法改成他们那种格式？
> 
> 是的，看一下该类播放器支持合并的结果格式是怎么样的，我看看能不能支持

我看了一下kodi iptv从插件的文档，看起来没有合并的功能。urls_limit = 1 的话得出来的结果也不是很好。看来只能放弃自动更新，隔段时间就手动生成后选合适的地址再重新编辑一份了

**Comment by qxsomeone** [comment]
请问，怎么在影视仓中调用txt？我是电视上直接安装了影视仓的APK，然后直接使用的github页面这个m3u地址。是否要使用这个json链接

接口源：
https://ghproxy.net/raw.githubusercontent.com/Guovin/TV/gd/output/result.m3u

数据源：
https://ghproxy.net/raw.githubusercontent.com/Guovin/TV/gd/source.json

**Comment by Guovin** [comment]
> 请问，怎么在影视仓中调用txt？我是电视上直接安装了影视仓的APK，然后直接使用的github页面这个m3u地址。是否要使用这个json链接
> 
> 接口源： https://ghproxy.net/raw.githubusercontent.com/Guovin/TV/gd/output/result.m3u
> 
> 数据源： https://ghproxy.net/raw.githubusercontent.com/Guovin/TV/gd/source.json

影视仓：
接口源： https://ghproxy.net/raw.githubusercontent.com/Guovin/TV/gd/output/result.txt
数据源可以使用上述json地址

**Comment by qxsomeone** [comment]
感谢。我回去试下
