### ISSUE TITLE
组播代码不能获取域名地址下的频道列表

### ISSUE THREAD

**Issue by mlzlzj** [Guovin/TV#410]
例如爬取湖南组播源，等于是打开http://tonkiang.us/hoteliptv.php输入湖南搜索，实际上除了[175.0.32.62:8081]这类纯数字的ip外还有[www.qhdrive.mi4.xyz:8888]这种域名加ip的，现在代码只能从纯数字ip+端口下解析出频道列表，实际上www.qhdrive.mi4.xyz:8888这个下也包含有282个频道列表，但代码不能解析出来，而且/udp/239.76.245.115:1234这类含udp的组播也没有解析出来，只有rtp的组播源，希望大佬升级一下代码，能解析出www.qhdrive.mi4.xyz:8888这类地址下包含的频道列表和含有udp的组播源。

**Comment by Guovin** [comment]
感谢反馈，该功能工作流已实现，其它运行方式待1.5.0发布

**Comment by Guovin** [comment]
已实现，请更新v1.5.0
