### ISSUE TITLE
没有可用数据

### ISSUE THREAD

**Issue by zzz0121** [Guovin/TV#421]
![image](https://github.com/user-attachments/assets/a5c46789-2528-404f-9e73-e931f3ac4b53)

**Comment by Guovin** [comment]
请更新最新代码后重试

**Comment by zzz0121** [comment]
就是最新代码
![image](https://github.com/user-attachments/assets/8327e371-8a04-4732-b8d6-2e8d8c278664)
有数据但是最后保存的为0感觉
![image](https://github.com/user-attachments/assets/17489cbe-198c-4e6e-bbdb-d6e5cc694d19)

**Comment by Guovin** [comment]
#423 解决了，再更新代码试试

**Comment by zzz0121** [comment]
什么问题呀这个是，我就是看我之前没更新代码的时候就这样，然后我更新完还是这样，我更新试一下

**Comment by Guovin** [comment]
解释一下，我看到你偏好设置了ipv6优先，由于github工作流对ipv6接口测速使用的是代理，有时可能并不那么准确。
如果你有备用的ipv6接口可以将其放到模板内（频道名称，接口地址)，如果更新获取不到ipv6的接口，开启了使用历史结果也会从模板中读取的。

**Comment by zzz0121** [comment]
ok，感谢

**Comment by zzz0121** [comment]
搜索ipv6但是都是一些ipv4源
![image](https://github.com/user-attachments/assets/85956d18-4bdb-4dfa-ba9a-2a15fa8d7851)

**Comment by Guovin** [comment]
这是因为工作流对于ipv6的验效并不时刻准确，结果中的ipv6时有时无属于正常情况。你的ipv_type设置了全部，当没有有效的ipv6时会用ipv4结果进行补充。如果想要准确结果建议本地运行。

**Comment by zzz0121** [comment]
好的，刚刚改了ipv_type
![image](https://github.com/user-attachments/assets/4f32b7de-74a1-4273-a92d-94402a970056)
结果还是不太行，我记得之前还是可以直接筛选出ipv6的，看来只能本地运行了，谢谢楼主我在看看

**Comment by Guovin** [comment]
#452 你的问题有可能跟这个相关，目前已经优化，请更新v1.5.0后再试试
