### ISSUE TITLE
txt转m3u问题

### ISSUE THREAD

**Issue by asxs123** [Guovin/TV#422]
def convert_to_m3u():函数遇到2列以上是数据会导致程序崩溃，开启订阅源功能后，部分订阅源可能存在不规范的格式，在获取阶段并没有对其进行处理，导致最终生成的txt文件中出现错误格式， def convert_to_m3u():函数处理到错误格式就会崩溃。

![image](https://github.com/user-attachments/assets/c96e7d6d-fb59-4d08-9af6-591477e10405)
如上图订阅源中   云南娱乐  出现了两个  ， 

![屏幕截图 2024-10-18 150049](https://github.com/user-attachments/assets/d71929dd-0035-483a-a6a6-906a4aa1b554)
报错日志

大佬能不能在获取订阅源的时候将获取到的源中，错误的格式规范成正确的格式，或者过滤掉这一行，避免在转m3u时出错

**Comment by Guovin** [comment]
感谢反馈，该功能工作流已优化实现，其它运行方式待1.5.0发布
