### ISSUE TITLE
关于docker设备的最低要求，与性价比最优选择（请大佬长期保留）

### ISSUE THREAD

**Issue by FRANKASEE** [Guovin/TV#426]
最近使用下来，个人觉得使用docker运行得到的结果最好。
结合个人最近的思考，想到很多人也会有此问题，为方便大家，希望在此讨论一下。

1、关于设备的最低要求才能满足一天2次的更新效率

2、关于 <50元、<100>、<150、<200各个阶段的硬件推荐

诚邀了解docker硬件的朋友发言推荐

**Comment by Guovin** [comment]
是设备条件不满足默认的单日运行两次频率吗？

**Comment by FRANKASEE** [comment]
有些设备价格便宜，但运行效率太低，比如s905的电视盒子。跑一次2个小时~~

**Comment by FRANKASEE** [comment]
目前在海鲜市场上看到有N1、s805电视盒子、玩客云，价格都还可以，就是不懂哪个性价比好

**Comment by Guovin** [comment]
> 有些设备价格便宜，但运行效率太低，比如s905的电视盒子。跑一次2个小时~~

配置较低的设备可以使用requests版本，效率会高一些

**Comment by FirewallChan** [comment]
可以考虑一下分开部署？docker容器用主力PC或者NAS服务器替代，然后汇总成m3u8，用web服务器等方式让盒子直接远程获取就好了

**Comment by Guovin** [comment]
因长时间较少人讨论此问题，暂时关闭。
