### ISSUE TITLE
程序闪退是何原因？

### ISSUE THREAD

**Issue by Ahhn1129** [Guovin/TV#429]
![无标题1](https://github.com/user-attachments/assets/b259d275-24c6-41a6-9d99-7de5a8ecc126)
出现此画面后光标转几圈后闪退，没有创建config或output文件夹，请问是何原因，Win 10系统。

**Comment by Guovin** [comment]
应该有报错日志输出，看能不能手快截图一下？或者以管理员运行

**Comment by Guovin** [comment]
应该有报错日志输出，看能不能手快截图一下？或者以管理员运行

**Comment by Guovin** [comment]
> 他应该是直接放在旧版本的文件夹下面的。 这样程序会自动调用原来的配置。
> 
> 但是！！！！新版本程序功能多了，调用旧配置会出错。

有这个可能，建议软件目录下不要使用旧配置，可能会出现读取问题。
我将在1.5.0优化这个问题，读取旧配置不存在的配置参数时使用默认值。

**Comment by Ahhn1129** [comment]
![2024-10-22 14-00-24 00_00_00-00_00_30](https://github.com/user-attachments/assets/28c025da-e680-48bb-8a32-3ea2c897e528)
你们说的都不存在，在单独的目录下，以管理员运行无任何输出和提示。

**Comment by Guovin** [comment]
有尝试过旧版能打开吗？

**Comment by Ahhn1129** [comment]
最早时1.40能打开，现在是所有版本都打不开。

**Comment by Guovin** [comment]
> 最早时1.40能打开，现在是所有版本都打不开。

好的，感谢尝试，具体原因我会去排查解决

**Comment by hkwpc** [comment]
我的也是这样，旧版本可以打开，新版本直接闪退，win10系统

**Comment by Guovin** [comment]
v1.5.1已更新，debug模式已经打开，请上传完整报错日志

**Comment by Guovin** [comment]
#536 win7那边出现了类似无法启动的问题，已经解决，不知道是否跟win10是同一个问题，请下载新版尝试，若有问题请上传报错日志，本问题暂时关闭。
