### ISSUE TITLE
一片空白

### ISSUE THREAD

**Issue by Amazon90** [Guovin/TV#430]
![image](https://github.com/user-attachments/assets/e8025e36-8e4c-45f6-a62d-63a1a3214692)
![image](https://github.com/user-attachments/assets/fd5c5300-ce4b-41f9-990b-d24c153f753d)
![image](https://github.com/user-attachments/assets/0417bd1e-8ae1-4bbf-949b-e8bfa6a8004f)

**Comment by Guovin** [comment]
有运行完成吗？容器日志看底部

**Comment by Guovin** [comment]
> > 有运行完成吗？容器日志看底部
> 
> 放弃了，花了很久时间但没有出来结果。

要运行完成才能访问结果链接的，requests版本一般10分钟左右就运行完成的了，可以查看最底部的输出内容，有提示的
