### ISSUE TITLE
链接后面的$1920x1080不要

### ISSUE THREAD

**Issue by wuyihuai** [Guovin/TV#431]
链接后面的$1920x1080、$LR•IPV4『线路28』|1920x1080不要添加上去，有些播放器不支持，导致不能播放。

**Comment by lzedwin** [comment]
赞同，或者做成个选项可以给用户选择是否添加

**Comment by Guovin** [comment]
#432 github最新代码已支持该功能，请更新并修改配置open_url_info = False即可实现

**Comment by Guovin** [comment]
已实现，请更新v1.5.0
