### ISSUE TITLE
ffmpeg安装好后，依然没办法用1.4.9版本对节目源进行筛选

### ISSUE THREAD

**Issue by lzedwin** [Guovin/TV#437]
![1](https://github.com/user-attachments/assets/40bcf34a-fba5-4720-834a-e32c45d49850)
![2](https://github.com/user-attachments/assets/c3abd704-111c-4901-ab57-aa389111cdee)
请问一下，为啥ffmpeg都安装好了，还是不能对节目源进行筛选？

**Comment by Guovin** [comment]
安装好就可以了，运行更新在测速阶段会自动调用的，当结果文件接口出现分辨率信息就说明是生效的

**Comment by lzedwin** [comment]
> 安装好就可以了，运行更新在测速阶段会自动调用的，当结果文件接口出现分辨率信息就说明是生效的

感谢大佬的及时回复，确实地址后面加上了$1920x1080。但失效的原地址没有筛选掉，希望能对失效的地址处理一下，更加方便后期的使用，感谢
