### ISSUE TITLE
有没有筛选工具，否则有点太多，如何筛选出来，本地访问速度比较好的节目源，每个频道保留几个就可以了。

### ISSUE THREAD

**Issue by fengshengxie** [Guovin/TV#445]
很多节目源访问起来比较卡顿

**Comment by Guovin** [comment]
目前默认ipv4和ipv6混合，如果你的网络支持ipv6，建议开启只获取ipv6接口，ipv_type = ipv6；
程序会将响应时间快和分辨率高的排序在前面，这是不用担心的，如果想要修改数量可以修改urls_limit;
如果符合你的网络的最佳播放效果，还是本地运行测速较佳，工作流会有误差。

**Comment by zzulpf** [comment]
> 目前默认ipv4和ipv6混合，如果你的网络支持ipv6，建议开启只获取ipv6接口，ipv_type = ipv6； 程序会将响应时间快和分辨率高的排序在前面，这是不用担心的，如果想要修改数量可以修改urls_limit; 如果符合你的网络的最佳播放效果，还是本地运行测速较佳，工作流会有误差。

大佬，本地运行的话生成的文件有没有办法上传到github的那个代理链接

**Comment by Guovin** [comment]
> > 目前默认ipv4和ipv6混合，如果你的网络支持ipv6，建议开启只获取ipv6接口，ipv_type = ipv6； 程序会将响应时间快和分辨率高的排序在前面，这是不用担心的，如果想要修改数量可以修改urls_limit; 如果符合你的网络的最佳播放效果，还是本地运行测速较佳，工作流会有误差。
> 
> 大佬，本地运行的话生成的文件有没有办法上传到github的那个代理链接

可以的，只要你把本地生成的结果文件上传到output/目录下就好了
