### ISSUE TITLE
关于更新

### ISSUE THREAD

**Issue by qxsomeone** [Guovin/TV#446]
请教一下，我是打算在安卓电视上，通过TVbox观看，  这个接口源
https://ghproxy.net/raw.githubusercontent.com/Guovin/TV/gd/output/result.m3u
是会自动更新吗？是否还要做其他设置

**Comment by Guovin** [comment]
是的，这是主仓库的默认输出结果，每天自动更新2次，不需要做其它操作

**Comment by qxsomeone** [comment]
多谢🙏
