### ISSUE TITLE
我在群晖使用docker搭建了，我要外网访问txt文件，是不是要把文件映射到网络才行？

### ISSUE THREAD

**Issue by a97313** [Guovin/TV#450]
我在群晖使用docker搭建了，我要外网访问txt文件，是不是要把文件映射到网络才行？

**Comment by Guovin** [comment]
是的，如果你的群辉ip不能在外网访问的话（默认端口8000），就需要对挂载的结果文件进行处理

**Comment by a97313** [comment]
我有公网，也有域名，我ip:8000/log和ip:8000/result都能查看，那我要访问output目录下的result.m3u或者txt路径是咋样的？是必须搞个站点放还是你docker里面有路径能直接访问？求教。

**Comment by Guovin** [comment]
如果你开启了open_m3u_result，ip:8000/result就是m3u的结果页面，否则就是txt的结果页面，这是查看纯文本的页面，如果播放器使用直接使用ip:8000即可
