### ISSUE TITLE
使用 GitHub Action，配置 ipv_type = ipv6 会返回 0 条

### ISSUE THREAD

**Issue by vsme** [Guovin/TV#452]
Your network does not support IPv6, using proxy instead

**Comment by Guovin** [comment]
并不是报错，这是提示，表示工作流的网络不支持ipv6，使用代理的方式进行接口测速

**Comment by vsme** [comment]
嗯，不好意思，是我表述有问题
```
ipv_type = ipv6
ipv_type_prefer = IPv6
ipv4_num = 6
ipv6_num = 6
```

问题在于这么设置后 返回 0 条
```
Total urls: 0, need to sort: 0
Sorting: 0it [00:00, ?it/s]
Checking if your network supports IPv6...

Writing: 0it [00:00, ?it/s]
Your network does not support IPv6, using proxy instead
Sorting: 0it [00:00, ?it/s]
```

**Comment by Guovin** [comment]
我查看了你的设置是没问题的，运行流程也没问题。问题是出在查询到的接口经过ipv6过滤后只有0条，也就是说明在测速前获取到的接口都是ipv4

**Comment by Guovin** [comment]
我查看了你的设置是没问题的，运行流程也没问题。问题是出在查询到的接口经过ipv6过滤后只有0条，也就是说明在测速前获取到的接口都是ipv4

**Comment by vsme** [comment]
问题是出在了订阅源上吗 subscribe_urls 全都不含有 ipv6

**Comment by vsme** [comment]
我看了下设置的订阅源是有ipv6的内容的，感觉是测速前过滤出了问题

**Comment by Guovin** [comment]
好的，具体我排查一下

**Comment by Guovin** [comment]
已修复，请更新v1.5.0
