### ISSUE TITLE
订阅源是不是不支持源中带有"$接口说明信息"的链接？

### ISSUE THREAD

**Issue by fichenx** [Guovin/TV#463]
docker部署，有几个问题向大佬了解一下。
1、配置参数subscribe_urls添加了这个订阅: http://itv.22m.top/ITVBox/tv/tvonline.txt ， 里面很多链接都带有“$接口说明信息”，而且里面的很多源质量还不错，但最后生成的文件里并没有这些链接，是不是不支持带有“$接口说明信息”的链接？
2、因为我的路由器设置了每天重启，重启后容器会自动运行一次并生成直播源，不想用容器自带的定时运行，我把配置参数open_service，设置了flase，但好像会导致容器不间断的运行并生成新的直播源，设置成True后正常。
3、能否增加频道名称自定义别名的功能，比如demo.txt里，频道名称可以改为CCTV-1:CCTV-1综合，最终生成的直播源频道名称为：CCTV-1综合。

**Comment by Guovin** [comment]
1.订阅支持获取带信息的链接，但处理过程会将这些信息移除，所以导致你结果看不到这些信息，具体你查一下结果中有没有这些链接即可
2.使用的是docker容器吗？路由器上面的？很可能是你设备原因导致重复运行，页面服务只不过是阻止了
3.没必要，模板只要按你想要的频道名称填写即可，CCTV-1综合进行查询时会合并CCTV-1的结果，反之一样

**Comment by fichenx** [comment]
好的，多谢大佬解惑
