### ISSUE TITLE
更新完成结果文件内部为空

### ISSUE THREAD

**Issue by molun** [Guovin/TV#464]
[result.log](https://github.com/user-attachments/files/17531334/result.log)
[result.txt](https://github.com/user-attachments/files/17531335/result.txt)

**Comment by biaji** [comment]
HTTPS proxies https://127.0.0.1:7890 are not supported, ignoring

代理关掉试试呢

**Comment by lzedwin** [comment]
<img width="718" alt="1" src="https://github.com/user-attachments/assets/789fe608-a0a5-430e-ad49-ca2bca50ce54">
我
<img width="402" alt="2" src="https://github.com/user-attachments/assets/5f49fe5e-5051-424d-b355-bc2ae915d374">
同样也有这样的问题，不作任何筛选的情况下，也不能输出任何源信息

**Comment by biaji** [comment]
我意思你是不是开了全局代理或者环境变量配置了代理了。 看7890应该是clash

**Comment by Guovin** [comment]
v1.5.1已更新，已修复该问题
