### ISSUE TITLE
open_m3u_result = False在影视仓中应该调用 txt，几乎都是重复的

### ISSUE THREAD

**Issue by a97313** [Guovin/TV#466]
open_m3u_result = False在影视仓中应该调用 txt，几乎都是重复的，有其他解决办法吗？

**Comment by lzedwin** [comment]
<img width="718" alt="1" src="https://github.com/user-attachments/assets/dbb3bf66-0711-4a0e-91f7-b4cd56ba04e8">
<img width="402" alt="2" src="https://github.com/user-attachments/assets/1c79076c-211c-4dc5-86f3-0635fe8453ee">
在没有作任何筛选的情况下，差不错500条源信息都产出不了一个源地址

**Comment by Guovin** [comment]
> open_m3u_result = False在影视仓中应该调用 txt，几乎都是重复的，有其他解决办法吗？

#403 @a97313 影视仓txt结果是不会重复的，只有m3u有这个情况，软件问题，暂无解

**Comment by Guovin** [comment]
@lzedwin 请开启新的issue讨论该问题，并将配置和模板发出，我这边没有复现你的这种情况
