### ISSUE TITLE
result文件不能产生源信息

### ISSUE THREAD

**Issue by lzedwin** [Guovin/TV#467]
<img width="718" alt="1" src="https://github.com/user-attachments/assets/d689be3e-0eee-46a9-a0e7-06dc2b25c027">
<img width="402" alt="2" src="https://github.com/user-attachments/assets/3a6fbc4e-273d-4051-8f99-00a25a7a56d2">
[demo.txt](https://github.com/user-attachments/files/17536853/demo.txt)
[result.txt](https://github.com/user-attachments/files/17536856/result.txt)
[config.txt](https://github.com/user-attachments/files/17536861/config.txt)
config.ini文件因为不能上传，我把扩展名改成txt了
我用了1.5.0版的docker版和win版都是跟截图一样，无论有没有“筛选”，结果有没有选“保留”，都跟我上传的result文件一样，没有产出源信息。我之前用同样的方法，在1.4.9版上200多个结果最少都有20-30个源信息产出，现在将近500个结果，都产出不了一个源信息，这是很奇怪的事情

**Comment by Guovin** [comment]
其它设置都是默认的吗？运行的是什么源获取方式？你的源主要是来源于哪里？会不会是偏好设置影响了？

**Comment by Guovin** [comment]
把config/config.ini文件发出来看看

**Comment by Guovin** [comment]
找到原因了，ipv6偏好这块有点问题，我处理一下，你先用回默认配置

**Comment by Guovin** [comment]
open_keep_all先改回False

**Comment by lzedwin** [comment]
> open_keep_all先改回False

可以生成源了，谢谢，大佬

**Comment by Guovin** [comment]
v1.5.1已更新，已修复该问题
