### ISSUE TITLE
建议增加频道或域名白名单

### ISSUE THREAD

**Issue by fichenx** [Guovin/TV#470]
ffmpeg对视频接口的测试有时会不准确。
比如：
http://tv.pull.hebtv.com/jishi/gonggongpindao.m3u8?t=2510710360&k=6c7672b94bb3940303bd8f5b81d4bdb6
这个接口总是进入不了最终生成的文件。可实际上是可以正常播放的，已经把分辨率筛选关闭（open_filter_resolution = False）。
有些频道的接口本来就不多，很容易漏掉。
能否增加一个频道或域名白名单，不用测试直接进入最终的生成文件，保证白名单内的频道有接口使用。

**Comment by Guovin** [comment]
感谢建议，该功能后续会增加

**Comment by Guovin** [comment]
v1.5.1已更新，已支持白名单功能，具体使用请查看教程
