### ISSUE TITLE
这demo的配置表单是不是可以优化一下。这问题好解决吗。小白的疑惑。

### ISSUE THREAD

**Issue by Heiwk** [Guovin/TV#473]
出现2个问题 ，
第一个【同名字的节目频道如果 多出特殊的符号并不会收集过来】。需要模板单独去添加。
例如CCTV1综合  那个CCTV1_电信 ，
凤凰中文。字体不一样繁体或者简体。
SiTV欢笑剧场和SiTV欢笑剧场_ 
这样多了一个下划线导致这节目并未收集到。
 需要单独增加这频道在demo内，可能被采集到结果文件里面去。
第二个【未检到任何源的频道】
会空置在原位置。
能否可以把未搜到结果的频道自定清理了，
或者归类到结果文件末尾处。方便处理。
能否节目单做这样的 排列。
 CCTV1综合：CCTV1#CCTV1综合#CCTv1#CCtv1
 凤凰卫视：凤凰卫视#鳳凰中文#凤凰中文台
这样冒号前面显示播放软件里面名称
#后面是出现的变化的节目名称他们会统一收集到一个节目频道里面去了。
这样搜集出来的数据不会因为细微了差异就被忽略掉了。
以上仅仅是自己使用后的感觉。具体的改动希望博主可以优化的更加好。

![5](https://github.com/user-attachments/assets/eb0ab44a-15bd-45b6-8b87-16c8fe7d6560)
![4](https://github.com/user-attachments/assets/a454d04f-0880-4f48-9a4b-b79639b57099)
![3](https://github.com/user-attachments/assets/83353292-1a75-498e-bf85-02a297378e3d)
![2](https://github.com/user-attachments/assets/ecc73418-dc28-4238-8569-289f2e0a968c)
![1](https://github.com/user-attachments/assets/02fb1491-276e-47cb-b988-7382f7cde136)

**Comment by Guovin** [comment]
1.程序已经处理特殊符号，你不必担心，输出结果名称以模板定义为准，相似的频道名称会合并结果（包括特殊符号、运营商、简繁体）
2.关于没有结果的频道归类到底部和自定义频道名称别名，会增加工作量影响效率，后面会考虑加上

**Comment by Guovin** [comment]
v1.5.1已更新，已支持无结果频道归类底部

**Comment by wy353208214** [comment]
请教一下，这个无结果频道，是不是demo.txt中没定义的频道会自动归类到底部？
我现在有个需求是，订阅源中的频道如何自动归类？比如像这个源[https://iptv-org.github.io/iptv/categories/animation.m3u](https://iptv-org.github.io/iptv/categories/animation.m3u)，我想把其归为Animation，在demo.txt中应该怎么添加才对？
我尝试这样添加，好像没有自动生成频道名称及其对应的频道。
`Animation,https://iptv-org.github.io/iptv/categories/animation.m3u`

感谢作者指出，谢谢~
