### ISSUE TITLE
为什么拉取的资源里面的ip都是ipv4的，没有ipv6的嘛？

### ISSUE THREAD

**Issue by a97313** [Guovin/TV#478]
为什么拉取的资源里面的ip都是ipv4的，没有ipv6的嘛？还是说有特殊的方式转过去

**Comment by Guovin** [comment]
如果你只要ipv6，需要修改ipv_type=ipv6，同时你的网络需要支持ipv6，如果不支持会使用代理测速，代理测速不稳定会导致没有ipv6结果。

**Comment by a97313** [comment]
> 如果你只要ipv6，需要修改ipv_type=ipv6，同时你的网络需要支持ipv6，如果不支持会使用代理测速，代理测速不稳定会导致没有ipv6结果。

需要修改完重启，重启会自动重新拉取吧？

**Comment by Guovin** [comment]
> > 如果你只要ipv6，需要修改ipv_type=ipv6，同时你的网络需要支持ipv6，如果不支持会使用代理测速，代理测速不稳定会导致没有ipv6结果。
> 
> 需要修改完重启，重启会自动重新拉取吧？

是的
