### ISSUE TITLE
open_m3u_result设置成了False依然输出的是m3u

### ISSUE THREAD

**Issue by iFoxox** [Guovin/TV#479]
docker-compose.yml:

services:
  tv-requests:
    image: guovern/tv-requests:latest
    ports:
      - "8000:8000"
    environment:
     open_m3u_result: False
    volumes:
      - /volume1/IPTV/config:/tv-requests/config
      - /volume1/IPTV/output:/tv-requests/output
    restart: always

访问http://IP:8000/result 却是m3u内容
![image](https://github.com/user-attachments/assets/147f832d-f749-4985-a955-8854594405b4)

**Comment by Guovin** [comment]
修改配置后有重启吗？

**Comment by Guovin** [comment]
配置不是通过环境变量修改的，需要修改挂载的config.ini文件后重启
