### ISSUE TITLE
自动更新应该没工作

### ISSUE THREAD

**Issue by dawnsummit** [Guovin/TV#480]
虽然crontab可以看见更新命令，但是更新命令应该没有成功运行。我手动测试了更新命令，每次都会提示8000端口已经被占用。应该是在更新之前需要杀掉之前的main.py进程才行。

**Comment by Guovin** [comment]
不需要杀进程，定时任务和页面服务不冲突。更新有没有成功应该检查结果文件的变化，而不是手动去执行，应该当前服务没有被停止，你再手动去执行肯定是端口被占用的。

**Comment by dawnsummit** [comment]
但是我看到生成的result这个文件一直没有按时更新过。

**Comment by dawnsummit** [comment]
sorry,忘了说一点，我看日志里面也没有显示有更新的内容。供你参考。

**Comment by Guovin** [comment]
最后一次结果文件更新时间是什么时候？是第一次运行完成的时间？把详细日志发出来看看
