### ISSUE TITLE
Docker已经启动了IPV6，然后容器状态也有ipv6输出，但是脚本拉取的地址的时候还是提示网络不支持ipv6

### ISSUE THREAD

**Issue by linianqing** [Guovin/TV#482]
Docker已经启动了IPV6，然后容器状态也有ipv6输出，但是脚本拉取的地址的时候还是提示网络不支持ipv6，
目前是飞牛DOCKER部署，然后1panel开启ipv6，容器状态显示已经启动了ipv6，网络使用bridge。
如图：
![容器状态1](https://github.com/user-attachments/assets/11ca0357-baf2-42c4-a337-d6c239f874dd)
![容器状态2](https://github.com/user-attachments/assets/17ee5fe3-e4aa-445b-83a0-ff31fa757e8f)
![Uploading ipv6.png…]()

**Comment by linianqing** [comment]
![ipv6](https://github.com/user-attachments/assets/0b1b8b23-ffe3-4557-afda-98cd879c8100)

**Comment by linianqing** [comment]
OK了，修改配置文件为ipv6就无视这个检测强制输出ipv6结果了。

**Comment by Guovin** [comment]
这个提示只是提示容器网络不支持ipv6，会使用代理的形式对ipv6接口进行测速，不影响结果是否输出ipv6。如果你的配置ipv_type_prefer偏好是自动，则会将ipv4作为优先结果，因为你的网络不支持ipv6。因此如果你想要结果中ipv6优先可以设置ipv_type_prefer=ipv6，或只有ipv6结果修改ipv_type=ipv6。

**Comment by linianqing** [comment]
感谢大佬
