### ISSUE TITLE
极空间部署，跑完后，output和config两个文件夹没有任何东西

### ISSUE THREAD

**Issue by Matthew1688** [Guovin/TV#485]
日志显示可以打开本地网址查看，但本地IP+端口无法打开，对应的output和config文件夹里面没有任何文件。请大神指教

**Comment by Kratos28** [comment]
等会试试

**Comment by Guovin** [comment]
请把运行日志发出来

**Comment by Matthew1688** [comment]
[2024_10_31 15_26_44_log.txt](https://github.com/user-attachments/files/17584454/2024_10_31.15_26_44_log.txt)
麻烦看一下，output和config两个文件还是空的

**Comment by Guovin** [comment]
看日志运行是没有问题的，你检查一下挂载命令路径是否正确

**Comment by Matthew1688** [comment]
![image](https://github.com/user-attachments/assets/6717ce3c-c331-4fc4-bbb0-e6b53f9d48ac)
我是手工创建的，方法应该跟符合命令行的要求

**Comment by Guovin** [comment]
config目录的内容是容器启动就会挂载完成的，不是等运行结束后才有的，如果你的config目录始终为空，说明挂载就出了问题。尝试删除容器后重新运行，或者进入容器查看对应文件夹是否有内容生成。

**Comment by Matthew1688** [comment]
已经删除多次重新部署都不行，极空间的容器路径好深，都不知道在哪里

**Comment by Guovin** [comment]
检查容器根目录下的tv-driver内的文件即可

**Comment by Guovin** [comment]
如果不是位于根目录，说明你上述的图片挂载tv-driver位置就已经错误了,所以没有结果文件
