### ISSUE TITLE
Docker环境安装,会自动更新最新版本的程序吗？

### ISSUE THREAD

**Issue by Kratos28** [Guovin/TV#495]
Docker环境安装,会自动更新最新版本的程序吗？

**Comment by Guovin** [comment]
docker每次更新需要重新拉取镜像

**Comment by Kratos28** [comment]
> docker每次更新需要重新拉取镜像

已经解决,使用watchtower容器自动更新

**Comment by Guovin** [comment]
> > docker每次更新需要重新拉取镜像
> 
> 已经解决,使用watchtower容器监听自动更新

可以的，本质上还是拉取最新镜像
