### ISSUE TITLE
【建议】增加客制化源合并功能

### ISSUE THREAD

**Issue by popmonker1** [Guovin/TV#497]
这个项目非常棒，一些比较偏门的地方电视台也能搜到，解决我们经常找源的麻烦，真的十分有用。提个小小的建议哈

【背景】
但是由于源的问题， 一般更新搜索到的源并不算太稳定，时效性也时好时坏，而大家手头上可能也有些常用频道也比较稳定的源。更新的源质量不好的情况下，无法使用自己固定的源，导致不停切换txt文件，稍有不便

【建议】
方案1：demo.txt中追加例外搜索项目，项目直接为客制化源，搜索完毕之后直接合并
方案2：追加customsource.txt文件，在更新的result.txt时候进行合并

**Comment by Guovin** [comment]
https://github.com/Guovin/TV/issues/421#issuecomment-2423744653
你说的需求程序本来已支持，只需在模板编辑即可

**Comment by Guovin** [comment]
模板中的接口是会作为历史结果补充到当初执行中

**Comment by popmonker1** [comment]
试了一下 #421方式 把频道（频道名称，接口地址）放入模板后，由于频道被误检测成无效源直接被删除了。
我查看了一下issue(#470 )其实是一致的，实际就是客制化相对稳定的一些源的频道不需要系统进行更新和验证，即白名单（和我提出的csutomsource.txt概念上变成一样了。
谢谢解答哈。

**Comment by Guovin** [comment]
白名单功能预计近期会更新
