### ISSUE TITLE
更新代码后BUG复现，IPV6可以获取链接但是结果为空

### ISSUE THREAD

**Issue by zzz0121** [Guovin/TV#500]
![image](https://github.com/user-attachments/assets/780fcec4-20a9-4a71-923c-084400b93f2d)

**Comment by Guovin** [comment]
不属于bug，工作流不支持ipv6网络，测速使用代理不稳定，若要稳定结果请本地运行

**Comment by Guovin** [comment]
如果保证ipv6地址可用，无需测速，可以关闭（open_sort=False），这样结果就能出来了

**Comment by zzz0121** [comment]
好的我试一下
