### ISSUE TITLE
直播链接文件里面许多url后面加了“$”后面却没跟内容导致播放软件崩溃

### ISSUE THREAD

**Issue by intersdp** [Guovin/TV#505]
![Screenshot_2024-11-04-13-09-07-45_4641ebc0df1485bf6b47ebd018b5ee76](https://github.com/user-attachments/assets/19f872da-d742-4c48-a4fa-02471b72cb72)
(就是例如如图这条“120.55.49.231:3095/rtp/233.50.201.246:5140$”结尾处的“$”后面没接任何文本，导致我使用的“影视OK版app”崩溃，请问能否将这些个“$”后面的内容补全？或是删除像这样后面不跟内容的$？)

**Comment by Guovin** [comment]
先修改open_url_info=False用着先

**Comment by Guovin** [comment]
v1.5.1已更新，已修复该问题
