### ISSUE TITLE
大佬，可以把最终文件的m3u格式文件也放在根目录吗

### ISSUE THREAD

**Issue by hncaiyin** [Guovin/TV#509]
1.生成的result.txt  result.m3u，只有result.txt复制到根目录下，请问把result.m3u也复制到根目录下，要怎么改代码呢，谢谢
2.申请添加“湖南都市频道”

**Comment by Guovin** [comment]
1.根目录的txt结果文件准备移除了，请从output目录下查看txt与m3u结果文件
2.地方频道后续会补充
