### ISSUE TITLE
可否新增屏蔽某个域名的源

### ISSUE THREAD

**Issue by vbskycn** [Guovin/TV#52]
如题
有些源：https://epg.pw/stream/d6cad1cb0bdc2192885f5fb7689d8234c282c7f07401c1093a000ab83142bd95.m3u8
这个epg.pw域下的源质量比较差
主要是放不出来的多
![image](https://github.com/Guovin/TV/assets/34542650/a90790d7-eee7-4aa6-bc5f-7b64255f5ddd)
而且失效的会显示上面这个动画，程序还检测不到失效

还有很多类型这样的源，显示他们的广告，就想请教一下，怎么在采集后屏蔽它们

**Comment by Guovin** [comment]
好问题，这确实是一个可以改善的地方。可以做到增加过滤指定域名接口，但也意味着该类域名如果可以正常播放也会被过滤掉，因为暂无法检测其是否播放广告内容。后续将增加自定义过滤指定域名接口配置项，我也将收集这类低质量域名作为默认值，欢迎提供。

**Comment by vbskycn** [comment]
除了默认值，最好是可以自定义
比如url里面包含   /udp 的可以排除  那种小水管组播源
key=txiptv   酒店源
.php?      每三方网站转发的源

**Comment by Guovin** [comment]
#58 该功能已发布，请更新v1.0.3
