### ISSUE TITLE
这2天一个节目没有出来，请教一下这怎么办 啊

### ISSUE THREAD

**Issue by Heiwk** [Guovin/TV#522]
全新docker下部署的
一下是错误日志
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=56727): Read timed out. (read timeout=120)")': /session/351af79df4897684f2203b51a8ab45fd/window
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=40607): Read timed out. (read timeout=120)")': /session/d5635155bda2ce60d34ab97346610459/window
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=56939): Read timed out. (read timeout=120)")': /session/36ca201d9463e5939110cbc2dccf3bd6/window
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=56939): Read timed out. (read timeout=120)")': /session/36ca201d9463e5939110cbc2dccf3bd6/window
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=58961): Read timed out. (read timeout=120)")': /session/3b150f6061a6c05edbd276e8712048b1/window
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=57371): Read timed out. (read timeout=120)")': /session/b83d78ccbb18b5b98042c586c4ebab16/window
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=60043): Read timed out. (read timeout=120)")': /session/bba414c04edafba06192469c3d16111f/window

我也没有修改其他的选项这是运行的日志查看结果，请问怎么处理大神能告诉一下？
![Uploading 34.gif…]()
![Uploading 11.png…]()

**Comment by hllkk** [comment]
TONKIANG 网站应该是开启了反爬虫，包括执之前的POST请求也不可以实现了，他们的POST传递的参数有变化了，导致的这个问题

**Comment by Guovin** [comment]
> TONKIANG 网站应该是开启了反爬虫，包括执之前的POST请求也不可以实现了，他们的POST传递的参数有变化了，导致的这个问题

并不是你描述的原因，日志显示是网球请求超时的原因，检查代理和ip是否有效就能解决该问题
