### ISSUE TITLE
组播的结果里会有需要输入用用户名密码的情况，测试的时候能否过滤掉？

### ISSUE THREAD

**Issue by larchsis** [Guovin/TV#525]
具体链接就补贴了，组播结果访问时，会提示输入用户名密码，这种安全加固过的能否在生成结果的时候检测到并删除？

**Comment by Guovin** [comment]
结果文件里面的接口吗？目前还没遇到过播放需要输入账号密码的情况

**Comment by Guovin** [comment]
如果是获取接口的过程中的这种情况，无需理会，程序只会解析json数据，如果无法获取json数据就会跳过。
