### ISSUE TITLE
同步上游代码的问题

### ISSUE THREAD

**Issue by vbskycn** [Guovin/TV#53]
很多人根本没有能力修改代码，但是却需要个人自己定义配置模板，比如我，增加了模板文件，会生成我需要的列表

但有个小问题，你的代码更新后，我同步上游就会有冲突， 就是result.log  这个文件

可否在使用了个人配置文件，也可以设置生成   user_result.log  ,这样同步你的最新代码就不会有冲突了

**Comment by Guovin** [comment]
请更新v1.0.2，只要存在user_config.py配置文件，日志将默认按user_result.log输出

**Comment by vbskycn** [comment]
已经收到更新，效率真高
