### ISSUE TITLE
是不是网络原因导致的一直失败。

### ISSUE THREAD

**Issue by cc0411** [Guovin/TV#530]
![image](https://github.com/user-attachments/assets/c37072d3-f472-4960-9235-db21a1c36e7c)
[root@node1 tvlist]# docker logs b2
Starting periodic command scheduler: cron.
Processing fofa for hotel: 100%|??????????| 45/45 [03:00<00:00,  4.01s/it]
Loading local multicast rtp files: 100%|??????????| 39/39 [00:21<00:00,  1.81it/s]
[root@node1 tvlist]# 
[root@node1 tvlist]# 
[root@node1 tvlist]# 
[root@node1 tvlist]# 
[root@node1 tvlist]# 
[root@node1 tvlist]# 
[root@node1 tvlist]# cat /tvlist/
config/ output/ 
[root@node1 tvlist]# cat /tvlist/output/result_new.log 
Exception managing chrome: error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json)
Exception managing chrome: error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json)
Exception managing chrome: error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json)
Exception managing chrome: error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json)
Exception managing chrome: error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json)
[root@node1 tvlist]# ls /tvlist/output/
result_new.log

**Comment by Guovin** [comment]
根据日志，初步结论是可能网络的原因
