### ISSUE TITLE
软件停止工作是啥原因啊

### ISSUE THREAD

**Issue by myyfan** [Guovin/TV#536]
[PYI-13644:DEBUG] LOADER: extracted pyimod02_importers
[PYI-13644:DEBUG] LOADER: running unmarshalled code object for module pyimod02_i
mporters...
[PYI-13644:DEBUG] LOADER: extracted pyimod03_ctypes
[PYI-13644:DEBUG] LOADER: running unmarshalled code object for module pyimod03_c
types...
[PYI-13644:DEBUG] LOADER: extracted pyimod04_pywin32
[PYI-13644:DEBUG] LOADER: running unmarshalled code object for module pyimod04_p
ywin32...
[PYI-13644:DEBUG] LOADER: looking for PYZ archive TOC entry...
[PYI-13644:DEBUG] LOADER: path to PYZ archive stored into sys._pyinstaller_pyz..
.
[PYI-13644:DEBUG] LOADER: running pyiboot01_bootstrap.py
[PYI-13644:DEBUG] LOADER: running pyi_rth_pkgres.py
[PYI-13644:DEBUG] LOADER: running pyi_rth_setuptools.py
[PYI-13644:DEBUG] LOADER: running pyi_rth_pkgutil.py
[PYI-13644:DEBUG] LOADER: running pyi_rth_inspect.py
[PYI-13644:DEBUG] LOADER: running pyi_rth_cryptography_openssl.py
[PYI-13644:DEBUG] LOADER: running pyi_rth_multiprocessing.py
[PYI-13644:DEBUG] LOADER: running pyi_rth__tkinter.py
[PYI-13644:DEBUG] LOADER: running tkinter_ui.py

问题签名:
  问题事件名称:	APPCRASH
  应用程序名:	iptv-update-tool.exe
  应用程序版本:	0.0.0.0
  应用程序时间戳:	672ddfb7
  故障模块名称:	_multiarray_umath.cp38-win32.pyd
  故障模块版本:	0.0.0.0
  故障模块时间戳:	6498fabf
  异常代码:	c000001d
  异常偏移:	000269c9
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by Guovin** [comment]
系统版本是什么？

**Comment by myyfan** [comment]
昨天在公司电脑上可以运行，家里电脑已崩溃，为此网上下了几个系统，重装了几次，都是这样

主机名:           WIN-2VVBUCHGJEV
OS 名称:          Microsoft Windows 7 旗舰版
OS 版本:          6.1.7601 Service Pack 1 Build 7601
OS 制造商:        Microsoft Corporation
OS 配置:          独立工作站
OS 构件类型:      Multiprocessor Free
注册的所有人:     MicroSoft
注册的组织:       MicroSoft
产品 ID:          00426-OEM-8992662-00006
初始安装日期:     2024/11/9, 9:21:49
系统启动时间:     2024/11/9, 9:22:30
系统制造商:       LENOVO
系统型号:         INVALID
系统类型:         x64-based PC
处理器:           安装了 1 个处理器。
                  [01]: Intel64 Family 6 Model 23 Stepping 10 GenuineIntel ~2508
 Mhz
BIOS 版本:        LENOVO 0FCN67WW, 2009/9/16
Windows 目录:     C:\Windows
系统目录:         C:\Windows\system32
启动设备:         \Device\HarddiskVolume1
系统区域设置:     zh-cn;中文(中国)
输入法区域设置:   zh-cn;中文(中国)
时区:             (UTC+08:00) 北京，重庆，香港特别行政区，乌鲁木齐
物理内存总量:     6,141 MB
可用的物理内存:   3,292 MB
虚拟内存: 最大值: 12,280 MB
虚拟内存: 可用:   7,126 MB
虚拟内存: 使用中: 5,154 MB
页面文件位置:     C:\pagefile.sys
域:               WORKGROUP
登录服务器:       \\WIN-2VVBUCHGJEV
修补程序:         安装了 40 个修补程序。
                  [01]: KB2849697
                  [02]: KB2849696
                  [03]: KB2841134
                  [04]: KB2841134
                  [05]: KB2670838
                  [06]: KB2830477
                  [07]: KB2592687
                  [08]: KB917607
                  [09]: KB2533552
                  [10]: KB2534111
                  [11]: KB2545698
                  [12]: KB2574819
                  [13]: KB2603229
                  [14]: KB2685811
                  [15]: KB2685813
                  [16]: KB2729094
                  [17]: KB2750841
                  [18]: KB2761217
                  [19]: KB2818604
                  [20]: KB2900986
                  [21]: KB3046269
                  [22]: KB3059317
                  [23]: KB3064209
                  [24]: KB3102429
                  [25]: KB3118401
                  [26]: KB3125574
                  [27]: KB3138612
                  [28]: KB3156016
                  [29]: KB3159398
                  [30]: KB3161102
                  [31]: KB3161949
                  [32]: KB3179573
                  [33]: KB3184143
                  [34]: KB4019990
                  [35]: KB4474419
                  [36]: KB4490628
                  [37]: KB5039339
                  [38]: KB5041942
                  [39]: KB976902
                  [40]: KB5041838

**Comment by Guovin** [comment]
既然下载了多次系统为什么不尝试win10或11呢，win7会有挺多未知的兼容性问题。
我刚上传了新版，做了尝试修复，先试试能不能运行。

**Comment by myyfan** [comment]
电脑太老了，09年的，现在用电脑用的太少了，再买一台又不划算，用 Win7速度也还过得去，再说也不太喜欢win10的界面。

**Comment by myyfan** [comment]
最新上传的版本正常了，感谢

**Comment by myyfan** [comment]
现在还有一个问题，就是图形界面运行的时候 selenium-manager.exe 会不停报运行停止，
命令行界面运行，会提示：“Message: Unable to obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location”，大佬能解决一下吗？
![微信截图_20241110122731](https://github.com/user-attachments/assets/f9fdcc10-0716-42c2-9185-78fcaf930226)

**Comment by Guovin** [comment]
> 现在还有一个问题，就是图形界面运行的时候 selenium-manager.exe 会不停报运行停止， 命令行界面运行，会提示：“Message: Unable to obtain driver for chrome; For documentation on this error, please visit: [https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location”，大佬能解决一下吗？](https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location%E2%80%9D%EF%BC%8C%E5%A4%A7%E4%BD%AC%E8%83%BD%E8%A7%A3%E5%86%B3%E4%B8%80%E4%B8%8B%E5%90%97%EF%BC%9F) ![微信截图_20241110122731](https://private-user-images.githubusercontent.com/8805868/384658699-f9fdcc10-0716-42c2-9185-78fcaf930226.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMTU3NzcsIm5iZiI6MTczMTIxNTQ3NywicGF0aCI6Ii84ODA1ODY4LzM4NDY1ODY5OS1mOWZkY2MxMC0wNzE2LTQyYzItOTE4NS03OGZjYWY5MzAyMjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTBUMDUxMTE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzY2NTM4ODUxOWY1ZDk2YmQ1YTVjMWM1N2UyYjlmYWFjYWZkNzM2Y2FlZDM4ZjRiZjk0NGU4MjY2Y2YyNjIzOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._hawYYi8eRNYYx_8zz9XKRG13tjWE_aYBx4SRZx_3zI)

你的电脑没装谷歌浏览器

**Comment by myyfan** [comment]
> > 现在还有一个问题，就是图形界面运行的时候 selenium-manager.exe 会不停报运行停止， 命令行界面运行，会提示：“Message: Unable to obtain driver for chrome; For documentation on this error, please visit: [https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location”，大佬能解决一下吗？](https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location%E2%80%9D%EF%BC%8C%E5%A4%A7%E4%BD%AC%E8%83%BD%E8%A7%A3%E5%86%B3%E4%B8%80%E4%B8%8B%E5%90%97%EF%BC%9F) ![微信截图_20241110122731](https://private-user-images.githubusercontent.com/8805868/384658699-f9fdcc10-0716-42c2-9185-78fcaf930226.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMTU3NzcsIm5iZiI6MTczMTIxNTQ3NywicGF0aCI6Ii84ODA1ODY4LzM4NDY1ODY5OS1mOWZkY2MxMC0wNzE2LTQyYzItOTE4NS03OGZjYWY5MzAyMjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTBUMDUxMTE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzY2NTM4ODUxOWY1ZDk2YmQ1YTVjMWM1N2UyYjlmYWFjYWZkNzM2Y2FlZDM4ZjRiZjk0NGU4MjY2Y2YyNjIzOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._hawYYi8eRNYYx_8zz9XKRG13tjWE_aYBx4SRZx_3zI)
> 
> 你的电脑没装谷歌浏览器

或许吧，但事实上我装了也一样，可能还是跟我的系统是WIN7有关系，老系统不再被支持了

**Comment by Guovin** [comment]
那你就去找合适的浏览器驱动安装了，或者关闭浏览器模式运行。软件启动问题已经解决，如果有别的问题就开新的issue，这个就关闭了。

**Comment by Guovin** [comment]
[numpy version](https://github.com/numpy/numpy/issues/24832#issuecomment-1741706225)
