### ISSUE TITLE
docker版能否增加不显示更新时间的选项。

### ISSUE THREAD

**Issue by riaiyuu** [Guovin/TV#539]
docker生成的源列表在首行显示更新时间，会占用1号台号，docker版能不能像GUI一样增加不显示更新时间功能的选项。

另外docker版没办法筛选无速度和速度很慢的源，有些速度200k以内的源基本没办法用，也可能是我配置文件的问题，我把我的配置文件贴出来，请大佬看一下有没有问题。

[config.txt](https://github.com/user-attachments/files/17687050/config.txt)

**Comment by Guovin** [comment]
1. gui所有功能docker都可使用，挂载后修改配置文件即可，具体见配置参数。
2. 只要开启了测速排序就不存在没办法筛选，程序会进行测速，结果按响应速度从快到慢依次排序。
