### ISSUE TITLE
大佬，小白求助

### ISSUE THREAD

**Issue by heshi2019** [Guovin/TV#540]
小白提问下哈，这个项目要怎么样使用

就是按照博主的操作设置后，怎样在potplayer这样的软件中使用

纯小白，如果打扰到了抱歉抱歉

**Comment by Guovin** [comment]
据反馈，使用这类播放器会有频道接口无法合并的问题，最好使用影视仓、影迷等播放器

**Comment by Eyion** [comment]
安装了TVBoxOSC，怎么把TV这个项目用起来？（TVBoxOSC项目没有Issues）

**Comment by Eyion** [comment]
安装了TVBoxOSC，怎么把TV这个项目用起来？（TVBoxOSC项目没有Issues）
