### ISSUE TITLE
订阅接口，是可以增加多少个，我添加些源进去感觉没用上啊

### ISSUE THREAD

**Issue by alantang1977** [Guovin/TV#545]
订阅接口，是可以增加多少个，我添加些源进去感觉没用上啊？

**Comment by Guovin** [comment]
订阅源个数没做限制，为什么会觉得没用上？

**Comment by alantang1977** [comment]
我添加了几个有广州综合源，但是最终只有一个链接，不知道是啥原因

**Comment by alantang1977** [comment]
subscribe_urls = https://aktv.top/live.txt,http://175.178.251.183:6689/live.txt,https://ghp.ci/https://raw.githubusercontent.com/joevess/IPTV/main/m3u/iptv.m3u,https://live.zbds.top/tv/iptv4.txt,https://anbox118.serv00.net/p3p.m3u.txt,https://dingyue.mytvsuper.xyz/myiptv.m3u,https://ghp.ci/https://raw.githubusercontent.com/kimwang1978/collect-tv-txt/main/merged_output.txt,https://4gtv.mytvsuper.xyz/myiptv.m3u,http://box.1890222.xyz:8081/iptv/live.m3u,http://itv.22m.top/ITVBox/tv/tvonline.txt,https://ghp.ci/https://raw.githubusercontent.com/wwb521/live/refs/heads/main/tv.m3u,https://ghp.ci/https://raw.githubusercontent.com/YanG-1989/m3u/refs/heads/main/Gather.m3u,https://ghp.ci/https://raw.githubusercontent.com/wwb521/live/main/tv.m3u,https://ghp.ci/https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u,https://ghp.ci/https://raw.githubusercontent.com/pizazzgy/tvbox/main/live.txt,https://m3u.ibert.me/txt/fmml_dv6.txt,https://m3u.ibert.me/txt/o_cn.txt,https://m3u.ibert.me/txt/j_iptv.txt,https://github.moeyy.xyz/https://raw.githubusercontent.com/PizazzGY/TVBox/main/live.txt,http://itv.22m.top/ITVBox/tv/tvonline.txt,https://live.fanmingming.com/tv/m3u/ipv6.m3u

**Comment by Guovin** [comment]
可能是因为经过测速后过滤了

**Comment by alantang1977** [comment]
明白了，我将测速调下试试，谢谢

**Comment by PQ0000** [comment]
你好，ok影视  tvbox类的软件没法支持吗？

**Comment by Guovin** [comment]
> 你好，ok影视 tvbox类的软件没法支持吗？

非本issue的问题请新建issue讨论，播放器兼容性支持问题并不是我能解决的，目前输出结果已经是通用格式，部分软件如tvbox需要软件作者解决，我有用过ok影视是可以正常使用的。
