### ISSUE TITLE
关于选择生成最佳源的问题

### ISSUE THREAD

**Issue by njmaojing** [Guovin/TV#552]
感谢作者的分享，以下是我对选择生成result的理解：
1、github action用的是共享runner跑出来的，对接口的测速也是在github runner上测出来的，与用户网络环境有差异，所以在本地播放效果也许不是最快的
2、本地电视使用应该在同局域网下选择iptv-update-tool，或者使用docker跑
所以说想要每天自动检测接口质量，用本地docker跑>github runner（或者说配置自己本地网络的runner，这个也不太现实）
以上如有错误，请作者指正，谢谢

**Comment by quanyu98** [comment]
对本地网络，这才有效，或者，指定地区爬出当天的，应该也可以使用，但是我指定地区爬不到，

**Comment by li5bo5** [comment]
那是不是意味着，正常家里使用的话，还是docker跑比较好？
毕竟runner和本地的网络必然是有差异的。
runner跑出来的结果，只能是确定源可用，是不是最佳还是存疑的

**Comment by Guovin** [comment]
是的，符合你本地播放网络的接口才是最佳的，工作流的测速会有误差（但也能用，可能会没那么准确）。
