### ISSUE TITLE
大佬你好，可否增加获取源

### ISSUE THREAD

**Issue by vbskycn** [Guovin/TV#56]
大佬你好，程序主要获取的是  www.foodieguide.com/iptvsearch/  网站搜索的源

可否增加一些源获取途径，比如现在最多的tvbox格式的直播源链接

因为github已经有大量的公开tvbox源了,而且很多也是经过测试的，这种格式也是本项目最终输出的格式

如果可以自由添加网络上公开的 tvbox格式的直播源链接，对于这些来源本项目 只做去重，速度排序，按模板输出需要的源

那获取的源将可以更加的全面

**Comment by vbskycn** [comment]
因为有很多公开源，  但是   [www.foodieguide.com/iptvsearch/](http://www.foodieguide.com/iptvsearch/)  上面并没有。

**Comment by Guovin** [comment]
是的，这个功能需求已经在排期了，请留意后续版本更新。
