### ISSUE TITLE
最新版本代码在获取订阅源后面的几条时，极其缓慢，大家有没有这个情况？还有，图形接口“显示无结果分类”设置后不会保存

### ISSUE THREAD

**Issue by myyfan** [Guovin/TV#564]
最新版本代码在获取订阅源后面的几条时，极其缓慢，大家有没有这个情况？还有，图形接口“显示无结果分类”设置后不会保存

**Comment by Guovin** [comment]
部分订阅源由于网络响应缓慢，所以会有延迟，属于正确现象。保存问题后续版本解决

**Comment by Guovin** [comment]
已修复，请更新v1.5.3

**Comment by Guovin** [comment]
> 为什么用docker安装后，访问界面一直是 ![1732001650376](https://private-user-images.githubusercontent.com/37065511/387545339-e754bd41-1abc-44f0-b6ab-d89f68822e0c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDIyNDMsIm5iZiI6MTczMjAwMTk0MywicGF0aCI6Ii8zNzA2NTUxMS8zODc1NDUzMzktZTc1NGJkNDEtMWFiYy00NGYwLWI2YWItZDg5ZjY4ODIyZTBjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA3MzkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNWIwZDE2OTg3NWFjMjA5NzUzNTM5YTVkMWFmNjE2YjU2NjA2NGMyNGEyZDMyZWY5Nzk5NmJmMjhhMmJmZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WGDVXYO-hkXiFDLb5USVF8oOKVuLxzqWuyTAlRUoDXs)

原因如文字所述，耐心一点，更新还没完成，具体可以去看日志输出

**Comment by DENGXUELIN** [comment]
快两天了，正常？








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Guovin/TV"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月19日(星期二) 下午3:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Guovin/TV] 最新版本代码在获取订阅源后面的几条时，极其缓慢，大家有没有这个情况？还有，图形接口“显示无结果分类”设置后不会保存 (Issue #564)





  
为什么用docker安装后，访问界面一直是 
  
原因如文字所述，耐心一点，更新还没完成，具体可以去看日志输出

**Comment by Guovin** [comment]
> 快两天了，正常？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Guovin/TV" ***@***.***&gt;; 发送时间:&nbsp;2024年11月19日(星期二) 下午3:40 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Guovin/TV] 最新版本代码在获取订阅源后面的几条时，极其缓慢，大家有没有这个情况？还有，图形接口“显示无结果分类”设置后不会保存 (Issue #564) 为什么用docker安装后，访问界面一直是 原因如文字所述，耐心一点，更新还没完成，具体可以去看日志输出 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

把容器日志发出来
