### ISSUE TITLE
最近出现这个错误：配置取得失败，length=1 index =1

### ISSUE THREAD

**Issue by sztuxp** [Guovin/TV#566]
本地docker安装，后台查看数据，结果都有了，但播放器拉数据，显示错误：“配置取得失败，length=1 index =1”
播放器：影视
result.m3u
#EXTM3U x-tvg-url="https://live.fanmingming.com/e.xml"
#EXTINF:-1 tvg-name="2024-11-17 09:10:29" tvg-logo="https://live.fanmingming.com/tv/2024-11-17 09:10:29.png" group-title="更新时间",2024-11-17 09:10:29
url
#EXTINF:-1 tvg-name="无线新闻" tvg-logo="https://live.fanmingming.com/tv/无线新闻.png" group-title="🌊港·澳·台",无线新闻
http://php.jdshipin.com:8880/smt.php?id=inews_twn$订阅源

**Comment by sztuxp** [comment]
我把两个结果文件 reult.m3u, result.txt复制到openwrt的www目录下，用ip/reult.m3u , ip/result.txt进行访问，发现result.txt正常，result.m3u出现一样的错误，应该是格式问题，播放器，影视，影视OK

**Comment by Guovin** [comment]
#550 https://github.com/Guovin/TV/issues/550#issuecomment-2470202803 一样的问题，是播放器的问题，可以修改部分配置进行兼容
