### ISSUE TITLE
在克隆的项目文件夹下cmd 第三串指令报错

### ISSUE THREAD

**Issue by 434387713** [Guovin/TV#567]
这个是啥情况啊，看不懂，有没有解决办法呀
![Uploading WindowsTerminal_JI3alNizqg.png…]()

**Comment by 434387713** [comment]
![WindowsTerminal_JI3alNizqg](https://github.com/user-attachments/assets/d874d1f4-4028-4eeb-be80-cdc45f4d66d4)

**Comment by Guovin** [comment]
下次报告报错问题，请将输出日志以文本内容发出来，不要用图片形式，谢谢

**Comment by 434387713** [comment]
> 下次报告报错问题，请将输出日志以文本内容发出来，不要用图片形式，谢谢

大佬，我刚接触这方面的东西，虽然在从其他方面学，还是不懂这些东西，不好意思给您添麻烦了。

输出日志一般情况下路径是哪个

下回有问题好找

**Comment by Guovin** [comment]
以后把上面图片中的代码选中复制出来就好了

**Comment by Guovin** [comment]
已修复，请更新v1.5.3

**Comment by LVS298** [comment]
界面跟新工具的组播源更新结果都是失效，觉得可以增加官方网站的直播源跟新功能，例如https://www.ncmc.nbtv.cn/gbds/folder8458/NBTV1/index.shtml
