### ISSUE TITLE
偏好设置结果优先无法对齐排列

### ISSUE THREAD

**Issue by FRANKASEE** [Guovin/TV#569]
结果协议优先选择IPV6，还会出现：
$IPV6
$IPV4
$IPV4
$IPV4
$IPV6
$IPV6

希望排列结果：
$IPV6
$IPV6
$IPV6
$IPV6
$IPV4
$IPV4
$IPV4
$IPV4
$IPV4

**Comment by Guovin** [comment]
把你的配置文件内容发出来看看？

**Comment by FRANKASEE** [comment]
晚上我回家发出来，在公司没有V6环境

**Comment by FRANKASEE** [comment]
更新到最新版本，已经没有此问题
