### ISSUE TITLE
获取列表后为什么会有一些失效的，有没有可能筛选一下出结果文件。

### ISSUE THREAD

**Issue by wyongmin** [Guovin/TV#574]
获取列表后为什么会有一些失效的，有没有可能筛选一下出结果文件。

**Comment by Guovin** [comment]
已经筛选响应超时失效的接口，但由于网络因素或测速不稳定可能会有误差。

**Comment by Guovin** [comment]
结果已经过滤响应超时失效的接口，但由于网络因素或测速不稳定可能会有误差。
