### ISSUE TITLE
本地执行报错

### ISSUE THREAD

**Issue by vbskycn** [Guovin/TV#72]
大佬你好，本地运行有些问题
ubuntu 22.04
开始缺少模块
pip install async_timeout   安装后好了
![image](https://github.com/Guovin/TV/assets/34542650/a998dad3-d38c-4c35-a34a-f51328e0c64f)
又提示这个，是说chrome驱动不对吗？
估计要环境正常还得上docker

**Comment by vbskycn** [comment]
换了一台又报别的错，环境配置太难了

![image](https://github.com/Guovin/TV/assets/34542650/cbb091f7-39ca-44fc-9ed5-dea8da431eb0)

**Comment by Guovin** [comment]
你先使用我的pipFile.lock，后面我会锁定依赖版本

**Comment by vbskycn** [comment]
好的
我试试
