### ISSUE TITLE
url解析需要修改了

### ISSUE THREAD

**Issue by LuckyLearning** [Guovin/TV#80]
今天抽空看了一下，发现直播都看不了了，一查，url是一周前的了，调试了一下，发现url全部解析成https://foodieguide.com/iptvsearch/donotsteal.m3u8

发现网站改dom了，加了节点
修改了一下取url的方式
def getUrlInfo(result):
    """
    Get the url, date and resolution
    """
    url = date = resolution = None
    result_div = [div for div in result.children if div.name == "div"]
    if 1 < len(result_div):
        channel_text = result_div[-2].get_text(strip=True)
     
我配置的是ipv6，话说你们的都是好的么？

**Comment by Guovin** [comment]
请更新最新代码，接口结构已经改了几次了，并不能保证当前版本代码能永久适用。
