### ISSUE TITLE
最新版1.06报错

### ISSUE THREAD

**Issue by vbskycn** [Guovin/TV#81]
![image](https://github.com/Guovin/TV/assets/34542650/9726ca7b-6e6f-459e-919c-357e37209a2d)

执行成功了，但是频道只有几个，查看记录，里面有报错。

![image](https://github.com/Guovin/TV/assets/34542650/d0d73de1-9dbe-4aaa-8b1a-90cbd1630787)

**Comment by vbskycn** [comment]
![image](https://github.com/Guovin/TV/assets/34542650/c34acd02-3255-46b1-9904-f314640e30b0)
查看log，也是0

**Comment by Guovin** [comment]
已解决，请更新v1.0.7
