### ISSUE TITLE
在win11 装了python 运行，不知道是什么原因

### ISSUE THREAD

**Issue by kelvinzhu120** [Guovin/TV#82]
Python 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> pip3 install pipenv
  File "<stdin>", line 1
    pip3 install pipenv
         ^^^^^^^
SyntaxError: invalid syntax

**Comment by Guovin** [comment]
看起来你是在python解释器中执行了命令，这是无法运行的。请至终端cmd中执行命令，前提是确保python已经添加到系统环境变量path中。
