### ISSUE TITLE
考虑添加Hotel IPTV吗？

### ISSUE THREAD

**Issue by yuanzl77** [Guovin/TV#90]
获取酒店提供得iptv直播源，是个不错的选择! 
http://tonkiang.us/hotellist.html?s=酒店ip&c=城市
fofa获取 公网IP "udpxy" && city="Shandong"(应该是能获取到，然后搜索看看有没有)直接搜索

**Comment by Guovin** [comment]
#112 增加了组播源功能，可以先试试看符不符合你的需求
