### ISSUE TITLE
bug:加了个人配置，没有输出

### ISSUE THREAD

**Issue by vbskycn** [Guovin/TV#91]
已经同步到最新代码了
设置了 user_demo
工作流成功运行
但是在.txt里面显示的还是user_demo.txt里面的内容
请帮排查一下是哪里的原因

**Comment by AomoDa** [comment]
#92  一样的问题

**Comment by Guovin** [comment]
请更新v1.0.8，这是因为某个节点修改了频道名称的检索参数，导致无法获取更新接口。当无法获取最新接口时，会默认使用回模板的接口。
